name: Phoenix CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-elixir@v2
        with:
          elixir-version: '1.17.3' # Adjust to your version
          otp-version: '27'     # Adjust to your version

      - name: Install dependencies
        run: mix deps.get

      - name: Set up the database
        run: mix ecto.create && mix ecto.migrate

      - name: Run tests
        run: mix test
